[book]
authors = ["Rabindra Dhakal"]
language = "en"
src = "src"
title = "soar documentation"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/pkgforge/soar"
additional-css = ["theme.css"]
